# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Next.js Server
    init: yarn
    command: yarn dev
  - name: Typescript Watcher
    init: tsc -w
# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
